Update readme file
rachaouldbabaali/todo-react-app pull request #1
Opened 2023-06-06 13:18 UTC by rachaouldbabaali

In this pull request, I have : 

- [x] Worked with React form and handling events.
- [x] Implemented CSS in the app.
- [x] Added edit feature.
- [x] Added delete feature.
- [x] Persisted React state in the local storage.
- [ ] Deployed the app on GitHub pages.

2023-06-08 06:35 UTC, momo-87 requested changes
Congratulations! 👏 👏 👏 
You did a great job implementing the main functionalities of the application.  👌 
Please take a look at the following feedback to build a complete React App.
![so_close1](https://github.com/rachaouldbabaali/todo-react-app/assets/122116375/fa9828c2-d220-4028-b3f9-23ce8d43734a)

# Highlights 
- Descriptive README.md file 👍 
- Use of .gitignore 👍 
- Good use of linters 👍 
- Correct use of Gitflow 👍 

# Required changes ♻️ 
_Check the comments under the review_

# Optional Suggestions 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding 👩‍💻 :code

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

#
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-08 06:35 UTC, momo-87 commented on src/components/ToDoApp.jsx
> +const TodoApp = () => (
[OPTIONAL] We suggest considering changing the name of the application to "ToDo App" instead of "React App"
![img1](https://github.com/rachaouldbabaali/todo-react-app/assets/122116375/191ccb5d-35f8-4d47-ba3e-c6eb7187b82c)

2023-06-08 06:35 UTC, momo-87 commented on src/components/ToDoApp.jsx
> +      <TodosLogic />
Your App doesn't include any navbar.  Create a navbar component and use React routes to navigate between the different parts of the application.
![img2](https://github.com/rachaouldbabaali/todo-react-app/assets/122116375/cc0a5e5a-5383-440e-8e49-72b161d6f180)

2023-06-09 00:14 UTC, rachaouldbabaali commented
Thank you @momo-87, I truly appreciate your time and efforts in reviewing my work, 
I would greatly appreciate it if you could take the time to review my work again and provide me with feedback.

2023-06-09 13:37 UTC, momo-87 approved these changes
# Status: Approved 💯 👏 👏 👏 
@rachaouldbabaali ! Well done.
Your project is completed. There is nothing other to say than it is time to merge it.
![Congratulation_stars](https://github.com/rachaouldbabaali/todo-react-app/assets/122116375/a830f8e0-efd6-4bbc-b5d3-68bffba51dab)

2023-06-20 07:46 UTC, rachaouldbabaali commented
Thank you, I truly appreciate your time and efforts in reviewing my work,

2023-06-20 07:46 UTC, merged